stages:
  - build
  - publish

before_script:
  - export BRANCH_NAME=${BRANCH_NAME:-master}
  - export DOCKER_REPOSITORY="canyan/janus-gateway"
  - export DOCKER_TAG=${DOCKER_TAG:-$BRANCH_NAME}
  - export DOCKER_IMAGE=$DOCKER_REPOSITORY:$DOCKER_TAG

build:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - apk add git
    - git clone https://github.com/meetecho/janus-gateway.git --branch $BRANCH_NAME --single-branch --depth=1
    - cd janus-gateway
    - docker build -t $DOCKER_IMAGE -f ../Dockerfile .
    - docker save $DOCKER_IMAGE > ../image.tar
  artifacts:
    expire_in: 2w
    paths:
      - image.tar
  tags:
    - docker

publish:
  image: docker
  stage: publish
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker load -i image.tar
    - echo -n $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker push $DOCKER_IMAGE
  tags:
    - docker
